services:
  backend:
    container_name: backend
    # image: fast
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      POSTGRES_SERVER: db
      POSTGRES_PASSWORD: password
    platform: linux/arm64 # (Patch for M1 Mac) Change Platform to linux/amd64 if you are on Linux
    build:
      context: ./backend

  frontend:
    container_name: frontend
    # image: react
    ports:
      - 5173:5173   
    restart: always
    build:
      context: ./frontend
    environment:
      - VITE_API_URL=http://localhost:8000

  db:
    container_name: database
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DEFAULT_DRIVER: pgsql

  proxymanager:
    image: "jc21/nginx-proxy-manager:latest"
    container_name: nginx_proxy_manager
    restart: always
    ports:
      - "443:443"
      - "8090:81"
    environment:
        DB_SQLITE_FILE: "/data/db.sqlite"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./proxy_params.conf:/etc/nginx/proxy_params.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
      - db
      - adminer
      - proxymanager

volumes:
  postgres_data:
  data:
  letsencrypt:
